PushPillServer/config/routes.rb
Rails.application.routes.draw do
  devise_for :doctor, controllers: { sessions: 'doctor/sessions', registrations: 'doctor/registrations' }
  devise_for :users, controllers: { sessions: 'user/sessions', registrations: 'user/registrations' }
  # devise_for :managers, class_name: "Admin::Manager", controllers: { sessions: 'admin/managers/sessions' }, skip: %i(registrations passwords)

  scope 'admin' do
    devise_for :managers, class_name: "Admin::Manager", controllers: { sessions: 'admin/manager/sessions' }#, skip: %i(registrations passwords)
  end

  namespace :admin do
    root 'home#index'

    resources :users, only: %i(index show) do
      member do
        post 'push'
      end
    end
  end

  namespace :api, defaults: {format: :json} do
    resource :doctor, controller: 'doctor' do
      resources :patients, only: %i(show index create destroy) do
        collection do
          get 'alert'
        end
        member do
          post 'push'
        end
      end
    end

    resource :user, controller: 'user' do
      collection do
        get 'patients'
      end
    end
    resources :pills do
      collection do
        get 'complete'
      end

      member do
        get 'check'
      end
    end
  end
end

PushPillServer/app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

PushPillServer/app/models/admin/manager.rb
class Admin::Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

PushPillServer/app/models/doctor.rb
class Doctor < ActiveRecord::Base
  acts_as_token_authenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :users
end

PushPillServer/app/models/pill.rb
class Pill < ActiveRecord::Base
  mount_uploader :image_path, ImageUploader

  belongs_to :user

  enum :week => [:sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday]
  enum :time => [:morning, :lunch, :dinner]

  TIME = %w(morning lunch dinner)
  WEEK = [['sunday', 'Sunday'], ['monday', 'Monday'], ['tuesday', 'Tuesday'], ['wednesday', 'Wednesday'], ['thursday', 'Thursday'], ['friday', 'Friday'], ['saturday', 'Saturday']]
end

PushPillServer/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_token_authenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :doctor
  has_many :pills
end

PushPillServer/app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController
end

PushPillServer/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def push
    @user = User.find_by_id(params[:id])
    unless @user.device_token
      render json: {}
      return
    end
    n = Rpush::Apns::Notification.new
    n.app = Rpush::Apns::App.find_by_name("ios_app")
    n.device_token = @user.device_token
    n.alert = params[:message]
    n.save!
    render json: {}
  end
end

PushPillServer/app/controllers/api/doctor_controller.rb
class Api::DoctorController < ApplicationController
  before_action :set_doctor

  private

  def set_doctor
    @doctor = Doctor.find_by_authentication_token(params[:token])
  end
end

PushPillServer/app/controllers/api/patients_controller.rb
class Api::PatientsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :set_doctor

  def index
    @patients = @doctor.users
  end

  def show
    @patient = @doctor.users.where('id = ?', params[:id]).first
  end

  def create
    @patient = User.find_by_id(params[:user_id])
    logger.debug @doctor
    @patient.doctor_id = @doctor.id
    @patient.save!
    render json: { success: true }
  end

  def destroy
    @patient = User.find_by_id(params[:id])
    @patient.doctor_id = nil
    @patient.save!
    render json: { success: true }
  end

  def alert
    @users = User.all.where('checked = ?', false)
  end

  def push
    @user = User.find_by_id(params[:id])
    unless @user.device_token
      render json: {}
      return
    end
    n = Rpush::Apns::Notification.new
    n.app = Rpush::Apns::App.find_by_name("ios_app")
    n.device_token = @user.device_token
    n.alert = params[:message]
    n.save!
    render json: {}
  end

  private

  def set_doctor
    @doctor = Doctor.find_by_authentication_token(params[:token])
  end
end

PushPillServer/app/controllers/api/pills_controller.rb
class Api::PillsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def show
    @pill = Pill.find_by_id(params[:id])
  end

  def new
    @pill = Pill.new
  end

  def create
    @pill = Pill.new(pill_params)

    if @pill.save
      render json: { success: true }
    end
  end

  def edit
    @pill = Pill.find_by_id(params[:id])
  end

  def update
    @pill = Pill.find_by_id(params[:id])

    if @pill.update(pill_params)
      render json: { success: true }
    end
  end

  def complete
    render 'api/pills/complete.html.erb'
  end

  def destroy
    @pill = Pill.find_by_id(params[:id])
    @pill.destroy
    render json: { success: true }
  end

  def check
    @pill = Pill.find_by_id(params[:id])
    @pill.checked = true
    @pill.save!
    render json: { success: true }
  end

  private

  def set_pill
    @pill = Pill.find_by_id(params[:id])
  end

  def pill_params
    params.require(:pill).permit(:name, :number, :days_of_week, :notes, :image_path, :time, :user_id)
  end
end

PushPillServer/app/controllers/api/user_controller.rb
class Api::UserController < ApplicationController
  def patients
    @users = User.where('doctor_id IS NULL')
  end

  def show
    @user = User.find_by_authentication_token(params[:token])
  end
end

PushPillServer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

PushPillServer/app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

PushPillServer/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

PushPillServer/app/helpers/api/application_helper.rb
module Api::ApplicationHelper
end

PushPillServer/app/helpers/api/doctor_helper.rb
module Api::DoctorHelper
end

PushPillServer/app/helpers/api/patients_helper.rb
module Api::PatientsHelper
end

PushPillServer/app/helpers/api/pills_helper.rb
module Api::PillsHelper
end

PushPillServer/app/helpers/api/user_helper.rb
module Api::UserHelper
end

PushPillServer/app/helpers/application_helper.rb
module ApplicationHelper
end

PushPillServer/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="ko">
<head>
  <title>Untitled5</title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="container">
  <nav class="navbar navbar-default">
    <div class="container-fluid">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= admin_root_path %>">무제</a> <!-- 서비스 이름 -->
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class=<%= 'active' if current_page?(admin_root_path) %>><a href="<%= admin_root_path %>">Home <span class="sr-only">(current)</span></a></li>
          <li class=<%= 'active' if request.path.include?('admin/users') %>><a href="<%= admin_users_path %>">Users</a></li>
          <!--<li class="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu">-->
          <!--<li><a href="#">Action</a></li>-->
          <!--<li><a href="#">Another action</a></li>-->
          <!--<li><a href="#">Something else here</a></li>-->
          <!--<li role="separator" class="divider"></li>-->
          <!--<li><a href="#">Separated link</a></li>-->
          <!--<li role="separator" class="divider"></li>-->
          <!--<li><a href="#">One more separated link</a></li>-->
          <!--</ul>-->
          <!--</li>-->
        </ul>
        <!--<form class="navbar-form navbar-left" role="search">-->
        <!--<div class="form-group">-->
        <!--<input type="text" class="form-control" placeholder="Search">-->
        <!--</div>-->
        <!--<button type="submit" class="btn btn-default">Submit</button>-->
        <!--</form>-->
        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if manager_signed_in? %>
                <%= link_to 'Logout', destroy_manager_session_path, method: 'delete' %>
            <% end %>
          </li>
          <!--<li class="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu">-->
          <!--<li><a href="#">Action</a></li>-->
          <!--<li><a href="#">Another action</a></li>-->
          <!--<li><a href="#">Something else here</a></li>-->
          <!--<li role="separator" class="divider"></li>-->
          <!--<li><a href="#">Separated link</a></li>-->
          <!--</ul>-->
          <!--</li>-->
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class='col-md-12'>
    <%= yield %>
  </div>
</div>
</body>
</html>

PushPillServer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PushPillServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>